import 'age_band.dart';
import 'milestone.dart';
import 'milestone_category.dart';

/// 組み込みの発達マイルストーンプリセット（54件）
///
/// 運動 / 言語 / 社会 / 認知 の4カテゴリを月齢順に網羅する。
/// [Milestone.l10nKey] は ARB の `milestoneXxx` キーに対応する。
const milestonesSeed = <Milestone>[
  // === 0〜1ヶ月 ===
  Milestone(
    id: 'first_gaze',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month0to1,
    l10nKey: 'milestoneFirstGaze',
    icon: '👀',
  ),
  Milestone(
    id: 'react_to_sound',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month0to1,
    l10nKey: 'milestoneReactToSound',
    icon: '🔔',
  ),
  Milestone(
    id: 'first_cry_meaning',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month0to1,
    l10nKey: 'milestoneFirstCryMeaning',
    icon: '😢',
  ),
  Milestone(
    id: 'grasp_reflex',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month0to1,
    l10nKey: 'milestoneGraspReflex',
    icon: '🤲',
  ),
  // === 1〜2ヶ月 ===
  Milestone(
    id: 'first_smile',
    category: MilestoneCategory.social,
    typicalAgeBand: AgeBand.month1to2,
    l10nKey: 'milestoneFirstSmile',
    icon: '😊',
  ),
  Milestone(
    id: 'lift_head',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month1to2,
    l10nKey: 'milestoneLiftHead',
    icon: '🙆',
  ),
  Milestone(
    id: 'coo_sound',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month1to2,
    l10nKey: 'milestoneCooSound',
    icon: '🗣️',
  ),
  Milestone(
    id: 'follow_object',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month1to2,
    l10nKey: 'milestoneFollowObject',
    icon: '👁️',
  ),
  // === 2〜4ヶ月 ===
  Milestone(
    id: 'social_smile',
    category: MilestoneCategory.social,
    typicalAgeBand: AgeBand.month2to4,
    l10nKey: 'milestoneSocialSmile',
    icon: '🥰',
  ),
  Milestone(
    id: 'hold_head_steady',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month2to4,
    l10nKey: 'milestoneHoldHeadSteady',
    icon: '🧒',
  ),
  Milestone(
    id: 'laugh_out_loud',
    category: MilestoneCategory.social,
    typicalAgeBand: AgeBand.month2to4,
    l10nKey: 'milestoneLaughOutLoud',
    icon: '😄',
  ),
  Milestone(
    id: 'reach_for_toy',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month2to4,
    l10nKey: 'milestoneReachForToy',
    icon: '🧸',
  ),
  Milestone(
    id: 'babble',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month2to4,
    l10nKey: 'milestoneBabble',
    icon: '💬',
  ),
  Milestone(
    id: 'recognize_parent',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month2to4,
    l10nKey: 'milestoneRecognizeParent',
    icon: '👨‍👩‍👧',
  ),
  // === 4〜6ヶ月 ===
  Milestone(
    id: 'rollover',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month4to6,
    l10nKey: 'milestoneRollover',
    icon: '🔄',
  ),
  Milestone(
    id: 'grab_object',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month4to6,
    l10nKey: 'milestoneGrabObject',
    icon: '✊',
  ),
  Milestone(
    id: 'sit_with_support',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month4to6,
    l10nKey: 'milestoneSitWithSupport',
    icon: '🪑',
  ),
  Milestone(
    id: 'respond_to_name',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month4to6,
    l10nKey: 'milestoneRespondToName',
    icon: '📛',
  ),
  Milestone(
    id: 'mouth_object',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month4to6,
    l10nKey: 'milestoneMouthObject',
    icon: '👅',
  ),
  Milestone(
    id: 'first_solid_food',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month4to6,
    l10nKey: 'milestoneFirstSolidFood',
    icon: '🥣',
  ),
  // === 6〜9ヶ月 ===
  Milestone(
    id: 'sit_unaided',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month6to9,
    l10nKey: 'milestoneSitUnaided',
    icon: '🧘',
  ),
  Milestone(
    id: 'crawl',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month6to9,
    l10nKey: 'milestoneCrawl',
    icon: '🐛',
  ),
  Milestone(
    id: 'first_tooth',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month6to9,
    l10nKey: 'milestoneFirstTooth',
    icon: '🦷',
  ),
  Milestone(
    id: 'say_mama_papa',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month6to9,
    l10nKey: 'milestoneSayMamaPapa',
    icon: '👶',
  ),
  Milestone(
    id: 'wave_bye',
    category: MilestoneCategory.social,
    typicalAgeBand: AgeBand.month6to9,
    l10nKey: 'milestoneWaveBye',
    icon: '👋',
  ),
  Milestone(
    id: 'pass_object',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month6to9,
    l10nKey: 'milestonePassObject',
    icon: '🤝',
  ),
  Milestone(
    id: 'peekaboo',
    category: MilestoneCategory.social,
    typicalAgeBand: AgeBand.month6to9,
    l10nKey: 'milestonePeekaboo',
    icon: '🙈',
  ),
  // === 9〜12ヶ月 ===
  Milestone(
    id: 'pull_to_stand',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month9to12,
    l10nKey: 'milestonePullToStand',
    icon: '🧍',
  ),
  Milestone(
    id: 'cruise_furniture',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month9to12,
    l10nKey: 'milestoneCruiseFurniture',
    icon: '🛋️',
  ),
  Milestone(
    id: 'pincer_grasp',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month9to12,
    l10nKey: 'milestonePincerGrasp',
    icon: '🤏',
  ),
  Milestone(
    id: 'clap_hands',
    category: MilestoneCategory.social,
    typicalAgeBand: AgeBand.month9to12,
    l10nKey: 'milestoneClapHands',
    icon: '👏',
  ),
  Milestone(
    id: 'understand_no',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month9to12,
    l10nKey: 'milestoneUnderstandNo',
    icon: '🙅',
  ),
  Milestone(
    id: 'point_at_things',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month9to12,
    l10nKey: 'milestonePointAtThings',
    icon: '👉',
  ),
  // === 12〜18ヶ月 ===
  Milestone(
    id: 'first_steps',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month12to18,
    l10nKey: 'milestoneFirstSteps',
    icon: '👣',
  ),
  Milestone(
    id: 'first_word',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month12to18,
    l10nKey: 'milestoneFirstWord',
    icon: '🔤',
  ),
  Milestone(
    id: 'drink_from_cup',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month12to18,
    l10nKey: 'milestoneDrinkFromCup',
    icon: '🥤',
  ),
  Milestone(
    id: 'stack_blocks',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month12to18,
    l10nKey: 'milestoneStackBlocks',
    icon: '🧱',
  ),
  Milestone(
    id: 'walk_well',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month12to18,
    l10nKey: 'milestoneWalkWell',
    icon: '🚶',
  ),
  Milestone(
    id: 'use_spoon',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month12to18,
    l10nKey: 'milestoneUseSpoon',
    icon: '🥄',
  ),
  Milestone(
    id: 'follow_instruction',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month12to18,
    l10nKey: 'milestoneFollowInstruction',
    icon: '📋',
  ),
  // === 18〜24ヶ月 ===
  Milestone(
    id: 'run',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month18to24,
    l10nKey: 'milestoneRun',
    icon: '🏃',
  ),
  Milestone(
    id: 'two_word_phrase',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month18to24,
    l10nKey: 'milestoneTwoWordPhrase',
    icon: '🗨️',
  ),
  Milestone(
    id: 'kick_ball',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month18to24,
    l10nKey: 'milestoneKickBall',
    icon: '⚽',
  ),
  Milestone(
    id: 'scribble',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month18to24,
    l10nKey: 'milestoneScribble',
    icon: '✏️',
  ),
  Milestone(
    id: 'name_body_parts',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month18to24,
    l10nKey: 'milestoneNameBodyParts',
    icon: '🧍',
  ),
  Milestone(
    id: 'pretend_play',
    category: MilestoneCategory.social,
    typicalAgeBand: AgeBand.month18to24,
    l10nKey: 'milestonePretendPlay',
    icon: '🎭',
  ),
  // === 24〜36ヶ月 ===
  Milestone(
    id: 'jump',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month24to36,
    l10nKey: 'milestoneJump',
    icon: '🦘',
  ),
  Milestone(
    id: 'short_sentence',
    category: MilestoneCategory.language,
    typicalAgeBand: AgeBand.month24to36,
    l10nKey: 'milestoneShortSentence',
    icon: '📣',
  ),
  Milestone(
    id: 'name_colors',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month24to36,
    l10nKey: 'milestoneNameColors',
    icon: '🎨',
  ),
  Milestone(
    id: 'sort_shapes',
    category: MilestoneCategory.cognitive,
    typicalAgeBand: AgeBand.month24to36,
    l10nKey: 'milestoneSortShapes',
    icon: '🔷',
  ),
  Milestone(
    id: 'potty_training',
    category: MilestoneCategory.social,
    typicalAgeBand: AgeBand.month24to36,
    l10nKey: 'milestonePottyTraining',
    icon: '🚽',
  ),
  Milestone(
    id: 'play_with_others',
    category: MilestoneCategory.social,
    typicalAgeBand: AgeBand.month24to36,
    l10nKey: 'milestonePlayWithOthers',
    icon: '👫',
  ),
  Milestone(
    id: 'climb_stairs',
    category: MilestoneCategory.motor,
    typicalAgeBand: AgeBand.month24to36,
    l10nKey: 'milestoneClimbStairs',
    icon: '🪜',
  ),
];
