#!/usr/bin/env python3
"""Add Baby Mile feature l10n keys to all 39 ARB files.

UI strings are translated for all 39 languages. Milestone preset titles are
translated for the 10 major markets; remaining languages reuse the English
title (concise developmental term, widely understood)."""
import json
import os
import collections

L10N_DIR = os.path.join(os.path.dirname(__file__), '..', 'lib', 'l10n')

# Map ARB file suffix -> translation locale key used in this script.
FILES = {
    'en': 'en', 'ja': 'ja', 'zh': 'zh', 'zh_Hant': 'zh_Hant', 'ko': 'ko',
    'de': 'de', 'fr': 'fr', 'fr_CA': 'fr', 'pt': 'pt', 'pt_PT': 'pt',
    'es': 'es', 'es_MX': 'es', 'it': 'it', 'hi': 'hi', 'ar': 'ar',
    'ca': 'ca', 'hr': 'hr', 'cs': 'cs', 'da': 'da', 'nl': 'nl',
    'en_AU': 'en', 'en_CA': 'en', 'en_GB': 'en', 'fi': 'fi', 'el': 'el',
    'he': 'he', 'hu': 'hu', 'id': 'id', 'ms': 'ms', 'no': 'no',
    'pl': 'pl', 'ro': 'ro', 'ru': 'ru', 'sk': 'sk', 'sv': 'sv',
    'th': 'th', 'tr': 'tr', 'uk': 'uk', 'vi': 'vi',
}

# ---- UI strings: per-locale translations (all 39 covered via base locale) ----
UI = collections.OrderedDict()

def ui(key, **vals):
    UI[key] = vals

ui('homeTabTitle', en='Home', ja='ホーム', zh='主页', zh_Hant='主頁', ko='홈', de='Start', fr='Accueil', pt='Início', es='Inicio', it='Home', hi='होम', ar='الرئيسية', ca='Inici', hr='Početna', cs='Domů', da='Hjem', nl='Start', fi='Koti', el='Αρχική', he='בית', hu='Kezdőlap', id='Beranda', ms='Laman', no='Hjem', pl='Główna', ro='Acasă', ru='Главная', sk='Domov', sv='Hem', th='หน้าแรก', tr='Ana Sayfa', uk='Головна', vi='Trang chủ')
ui('checklistTabTitle', en='Checklist', ja='チェックリスト', zh='清单', zh_Hant='清單', ko='체크리스트', de='Checkliste', fr='Liste', pt='Lista', es='Lista', it='Lista', hi='चेकलिस्ट', ar='قائمة', ca='Llista', hr='Popis', cs='Seznam', da='Tjekliste', nl='Lijst', fi='Lista', el='Λίστα', he='רשימה', hu='Lista', id='Daftar', ms='Senarai', no='Sjekkliste', pl='Lista', ro='Listă', ru='Список', sk='Zoznam', sv='Lista', th='เช็คลิสต์', tr='Liste', uk='Список', vi='Danh sách')
ui('timelineTabTitle', en='Timeline', ja='タイムライン', zh='时间线', zh_Hant='時間軸', ko='타임라인', de='Verlauf', fr='Chronologie', pt='Linha do tempo', es='Cronología', it='Cronologia', hi='टाइमलाइन', ar='الجدول الزمني', ca='Cronologia', hr='Vremenska crta', cs='Časová osa', da='Tidslinje', nl='Tijdlijn', fi='Aikajana', el='Χρονολόγιο', he='ציר זמן', hu='Idővonal', id='Linimasa', ms='Garis masa', no='Tidslinje', pl='Oś czasu', ro='Cronologie', ru='Лента', sk='Časová os', sv='Tidslinje', th='ไทม์ไลน์', tr='Zaman Çizelgesi', uk='Стрічка', vi='Dòng thời gian')
ui('cardTabTitle', en='Cards', ja='カード', zh='卡片', zh_Hant='卡片', ko='카드', de='Karten', fr='Cartes', pt='Cartões', es='Tarjetas', it='Carte', hi='कार्ड', ar='البطاقات', ca='Targetes', hr='Kartice', cs='Karty', da='Kort', nl='Kaarten', fi='Kortit', el='Κάρτες', he='כרטיסים', hu='Kártyák', id='Kartu', ms='Kad', no='Kort', pl='Karty', ro='Carduri', ru='Карточки', sk='Karty', sv='Kort', th='การ์ด', tr='Kartlar', uk='Картки', vi='Thẻ')
ui('settingsTabTitle', en='Settings', ja='設定', zh='设置', zh_Hant='設定', ko='설정', de='Einstellungen', fr='Réglages', pt='Definições', es='Ajustes', it='Impostazioni', hi='सेटिंग्स', ar='الإعدادات', ca='Configuració', hr='Postavke', cs='Nastavení', da='Indstillinger', nl='Instellingen', fi='Asetukset', el='Ρυθμίσεις', he='הגדרות', hu='Beállítások', id='Pengaturan', ms='Tetapan', no='Innstillinger', pl='Ustawienia', ro='Setări', ru='Настройки', sk='Nastavenia', sv='Inställningar', th='ตั้งค่า', tr='Ayarlar', uk='Налаштування', vi='Cài đặt')

ui('homeGreeting', en='{name}', ja='{name}', zh='{name}', zh_Hant='{name}', ko='{name}', de='{name}', fr='{name}', pt='{name}', es='{name}', it='{name}', hi='{name}', ar='{name}', ca='{name}', hr='{name}', cs='{name}', da='{name}', nl='{name}', fi='{name}', el='{name}', he='{name}', hu='{name}', id='{name}', ms='{name}', no='{name}', pl='{name}', ro='{name}', ru='{name}', sk='{name}', sv='{name}', th='{name}', tr='{name}', uk='{name}', vi='{name}', _ph={'name': {}})
ui('ageMonths', en='{months} months', ja='生後{months}ヶ月', zh='{months}个月', zh_Hant='{months}個月', ko='{months}개월', de='{months} Monate', fr='{months} mois', pt='{months} meses', es='{months} meses', it='{months} mesi', hi='{months} माह', ar='{months} أشهر', ca='{months} mesos', hr='{months} mj.', cs='{months} měsíců', da='{months} måneder', nl='{months} maanden', fi='{months} kk', el='{months} μήνες', he='{months} חודשים', hu='{months} hónap', id='{months} bulan', ms='{months} bulan', no='{months} måneder', pl='{months} mies.', ro='{months} luni', ru='{months} мес.', sk='{months} mesiacov', sv='{months} månader', th='{months} เดือน', tr='{months} ay', uk='{months} міс.', vi='{months} tháng', _ph={'months': {'type': 'int'}})
ui('recentMilestones', en='Recent Milestones', ja='最近の記録', zh='最近的里程碑', zh_Hant='最近的里程碑', ko='최근 기록', de='Letzte Meilensteine', fr='Jalons récents', pt='Marcos recentes', es='Hitos recientes', it='Tappe recenti', hi='हाल के पड़ाव', ar='أحدث الإنجازات', ca='Fites recents', hr='Nedavne prekretnice', cs='Nedávné milníky', da='Seneste milepæle', nl='Recente mijlpalen', fi='Viimeisimmät', el='Πρόσφατα', he='אבני דרך אחרונות', hu='Legutóbbiak', id='Tonggak terbaru', ms='Pencapaian terkini', no='Siste milepæler', pl='Ostatnie kamienie', ro='Repere recente', ru='Недавние события', sk='Nedávne míľniky', sv='Senaste milstolpar', th='ความก้าวหน้าล่าสุด', tr='Son kilometre taşları', uk='Останні події', vi='Cột mốc gần đây')
ui('thisMonthChecklist', en='Milestones to Check This Month', ja='今月チェックすべき発達', zh='本月发育检查', zh_Hant='本月發育檢查', ko='이번 달 발달 체크', de='Diesen Monat prüfen', fr='À vérifier ce mois', pt='Verificar este mês', es='Comprobar este mes', it='Da verificare questo mese', hi='इस माह जांचें', ar='تحقق هذا الشهر', ca="Comprova aquest mes", hr='Provjeri ovaj mjesec', cs='Zkontrolovat tento měsíc', da='Tjek denne måned', nl='Deze maand', fi='Tarkista tässä kuussa', el='Έλεγχος αυτόν τον μήνα', he='לבדוק החודש', hu='Ebben a hónapban', id='Periksa bulan ini', ms='Semak bulan ini', no='Sjekk denne måneden', pl='Sprawdź w tym miesiącu', ro='De verificat luna aceasta', ru='Проверить в этом месяце', sk='Skontrolovať tento mesiac', sv='Kolla denna månad', th='ตรวจสอบเดือนนี้', tr='Bu ay kontrol et', uk='Перевірити цього місяця', vi='Kiểm tra tháng này')
ui('recordMilestone', en='Record Milestone', ja='マイルストーンを記録', zh='记录里程碑', zh_Hant='記錄里程碑', ko='기록 추가', de='Meilenstein erfassen', fr='Enregistrer un jalon', pt='Registar marco', es='Registrar hito', it='Registra tappa', hi='पड़ाव दर्ज करें', ar='سجّل إنجازًا', ca='Registra una fita', hr='Zabilježi prekretnicu', cs='Zaznamenat milník', da='Registrer milepæl', nl='Mijlpaal vastleggen', fi='Tallenna virstanpylväs', el='Καταγραφή', he='תיעוד אבן דרך', hu='Mérföldkő rögzítése', id='Catat tonggak', ms='Rekod pencapaian', no='Registrer milepæl', pl='Zapisz kamień milowy', ro='Înregistrează reper', ru='Записать событие', sk='Zaznamenať míľnik', sv='Registrera milstolpe', th='บันทึกความก้าวหน้า', tr='Kilometre taşı kaydet', uk='Записати подію', vi='Ghi cột mốc')
ui('makeCard', en='Make a Card', ja='カードを作る', zh='制作卡片', zh_Hant='製作卡片', ko='카드 만들기', de='Karte erstellen', fr='Créer une carte', pt='Criar cartão', es='Crear tarjeta', it='Crea una carta', hi='कार्ड बनाएँ', ar='إنشاء بطاقة', ca='Crea una targeta', hr='Napravi karticu', cs='Vytvořit kartu', da='Lav et kort', nl='Kaart maken', fi='Tee kortti', el='Δημιουργία κάρτας', he='יצירת כרטיס', hu='Kártya készítése', id='Buat kartu', ms='Buat kad', no='Lag et kort', pl='Utwórz kartę', ro='Creează card', ru='Создать карточку', sk='Vytvoriť kartu', sv='Skapa kort', th='สร้างการ์ด', tr='Kart oluştur', uk='Створити картку', vi='Tạo thẻ')
ui('noMilestonesYet', en='No milestones recorded yet', ja='まだ記録がありません', zh='还没有记录', zh_Hant='還沒有記錄', ko='아직 기록이 없습니다', de='Noch keine Meilensteine', fr='Aucun jalon enregistré', pt='Nenhum marco registado', es='Aún no hay hitos', it='Nessuna tappa registrata', hi='अभी कोई रिकॉर्ड नहीं', ar='لا توجد إنجازات بعد', ca='Encara no hi ha fites', hr='Još nema prekretnica', cs='Zatím žádné milníky', da='Ingen milepæle endnu', nl='Nog geen mijlpalen', fi='Ei vielä merkintöjä', el='Καμία καταγραφή ακόμη', he='אין עדיין אבני דרך', hu='Még nincs mérföldkő', id='Belum ada catatan', ms='Belum ada rekod', no='Ingen milepæler ennå', pl='Brak kamieni milowych', ro='Niciun reper încă', ru='Пока нет записей', sk='Zatiaľ žiadne míľniky', sv='Inga milstolpar ännu', th='ยังไม่มีบันทึก', tr='Henüz kayıt yok', uk='Поки немає записів', vi='Chưa có cột mốc')
ui('selectPreset', en='Choose a milestone', ja='マイルストーンを選ぶ', zh='选择里程碑', zh_Hant='選擇里程碑', ko='기록 선택', de='Meilenstein wählen', fr='Choisir un jalon', pt='Escolher marco', es='Elegir hito', it='Scegli una tappa', hi='पड़ाव चुनें', ar='اختر إنجازًا', ca='Tria una fita', hr='Odaberi prekretnicu', cs='Vyber milník', da='Vælg milepæl', nl='Kies mijlpaal', fi='Valitse virstanpylväs', el='Επιλέξτε', he='בחר אבן דרך', hu='Válassz mérföldkövet', id='Pilih tonggak', ms='Pilih pencapaian', no='Velg milepæl', pl='Wybierz kamień', ro='Alege reper', ru='Выберите событие', sk='Vyber míľnik', sv='Välj milstolpe', th='เลือกความก้าวหน้า', tr='Kilometre taşı seç', uk='Оберіть подію', vi='Chọn cột mốc')
ui('customMilestone', en='Custom', ja='自由入力', zh='自定义', zh_Hant='自訂', ko='직접 입력', de='Eigene', fr='Personnalisé', pt='Personalizado', es='Personalizado', it='Personalizzato', hi='कस्टम', ar='مخصص', ca='Personalitzat', hr='Prilagođeno', cs='Vlastní', da='Tilpasset', nl='Aangepast', fi='Mukautettu', el='Προσαρμοσμένο', he='מותאם', hu='Egyéni', id='Khusus', ms='Tersuai', no='Egendefinert', pl='Własne', ro='Personalizat', ru='Своё', sk='Vlastné', sv='Anpassad', th='กำหนดเอง', tr='Özel', uk='Власне', vi='Tùy chỉnh')
ui('milestoneTitleLabel', en='Title', ja='タイトル', zh='标题', zh_Hant='標題', ko='제목', de='Titel', fr='Titre', pt='Título', es='Título', it='Titolo', hi='शीर्षक', ar='العنوان', ca='Títol', hr='Naslov', cs='Název', da='Titel', nl='Titel', fi='Otsikko', el='Τίτλος', he='כותרת', hu='Cím', id='Judul', ms='Tajuk', no='Tittel', pl='Tytuł', ro='Titlu', ru='Название', sk='Názov', sv='Titel', th='ชื่อ', tr='Başlık', uk='Назва', vi='Tiêu đề')
ui('selectDate', en='Date', ja='日付', zh='日期', zh_Hant='日期', ko='날짜', de='Datum', fr='Date', pt='Data', es='Fecha', it='Data', hi='तारीख', ar='التاريخ', ca='Data', hr='Datum', cs='Datum', da='Dato', nl='Datum', fi='Päivä', el='Ημερομηνία', he='תאריך', hu='Dátum', id='Tanggal', ms='Tarikh', no='Dato', pl='Data', ro='Data', ru='Дата', sk='Dátum', sv='Datum', th='วันที่', tr='Tarih', uk='Дата', vi='Ngày')
ui('addPhoto', en='Add Photo', ja='写真を追加', zh='添加照片', zh_Hant='新增照片', ko='사진 추가', de='Foto hinzufügen', fr='Ajouter une photo', pt='Adicionar foto', es='Añadir foto', it='Aggiungi foto', hi='फ़ोटो जोड़ें', ar='إضافة صورة', ca='Afegeix foto', hr='Dodaj fotografiju', cs='Přidat fotku', da='Tilføj foto', nl='Foto toevoegen', fi='Lisää kuva', el='Προσθήκη φωτό', he='הוסף תמונה', hu='Fotó hozzáadása', id='Tambah foto', ms='Tambah foto', no='Legg til bilde', pl='Dodaj zdjęcie', ro='Adaugă foto', ru='Добавить фото', sk='Pridať fotku', sv='Lägg till foto', th='เพิ่มรูป', tr='Fotoğraf ekle', uk='Додати фото', vi='Thêm ảnh')
ui('takePhoto', en='Take Photo', ja='カメラで撮影', zh='拍照', zh_Hant='拍照', ko='사진 촬영', de='Foto aufnehmen', fr='Prendre une photo', pt='Tirar foto', es='Tomar foto', it='Scatta foto', hi='फ़ोटो लें', ar='التقط صورة', ca='Fes una foto', hr='Snimi fotografiju', cs='Vyfotit', da='Tag foto', nl='Foto maken', fi='Ota kuva', el='Λήψη φωτό', he='צלם תמונה', hu='Fénykép', id='Ambil foto', ms='Ambil foto', no='Ta bilde', pl='Zrób zdjęcie', ro='Fă o poză', ru='Сделать фото', sk='Odfotiť', sv='Ta foto', th='ถ่ายรูป', tr='Fotoğraf çek', uk='Зробити фото', vi='Chụp ảnh')
ui('chooseFromLibrary', en='Choose from Library', ja='ライブラリから選ぶ', zh='从相册选择', zh_Hant='從相簿選擇', ko='앨범에서 선택', de='Aus Galerie wählen', fr='Choisir dans la galerie', pt='Escolher da galeria', es='Elegir de la galería', it='Scegli dalla galleria', hi='लाइब्रेरी से चुनें', ar='اختر من المكتبة', ca='Tria de la galeria', hr='Odaberi iz galerije', cs='Vybrat z galerie', da='Vælg fra bibliotek', nl='Kies uit bibliotheek', fi='Valitse kirjastosta', el='Επιλογή από συλλογή', he='בחר מהספרייה', hu='Választás a tárból', id='Pilih dari galeri', ms='Pilih dari galeri', no='Velg fra bibliotek', pl='Wybierz z galerii', ro='Alege din galerie', ru='Выбрать из галереи', sk='Vybrať z galérie', sv='Välj från bibliotek', th='เลือกจากคลัง', tr='Galeriden seç', uk='Вибрати з галереї', vi='Chọn từ thư viện')
ui('memoLabel', en='Note', ja='メモ', zh='备注', zh_Hant='備註', ko='메모', de='Notiz', fr='Note', pt='Nota', es='Nota', it='Nota', hi='नोट', ar='ملاحظة', ca='Nota', hr='Bilješka', cs='Poznámka', da='Note', nl='Notitie', fi='Muistiinpano', el='Σημείωση', he='הערה', hu='Jegyzet', id='Catatan', ms='Nota', no='Notat', pl='Notatka', ro='Notă', ru='Заметка', sk='Poznámka', sv='Anteckning', th='บันทึก', tr='Not', uk='Нотатка', vi='Ghi chú')
ui('memoHint', en='Add a note (optional)', ja='メモを入力（任意）', zh='添加备注（可选）', zh_Hant='新增備註（選填）', ko='메모 입력 (선택)', de='Notiz hinzufügen (optional)', fr='Ajouter une note (facultatif)', pt='Adicionar nota (opcional)', es='Añadir nota (opcional)', it='Aggiungi nota (facoltativo)', hi='नोट जोड़ें (वैकल्पिक)', ar='أضف ملاحظة (اختياري)', ca='Afegeix una nota (opcional)', hr='Dodaj bilješku (opcionalno)', cs='Přidat poznámku (volitelné)', da='Tilføj note (valgfrit)', nl='Notitie toevoegen (optioneel)', fi='Lisää muistiinpano (valinnainen)', el='Προσθήκη σημείωσης (προαιρετικό)', he='הוסף הערה (אופציונלי)', hu='Jegyzet hozzáadása (opcionális)', id='Tambah catatan (opsional)', ms='Tambah nota (pilihan)', no='Legg til notat (valgfritt)', pl='Dodaj notatkę (opcjonalnie)', ro='Adaugă o notă (opțional)', ru='Добавить заметку (необязательно)', sk='Pridať poznámku (voliteľné)', sv='Lägg till anteckning (valfritt)', th='เพิ่มบันทึก (ไม่บังคับ)', tr='Not ekle (isteğe bağlı)', uk='Додати нотатку (необов’язково)', vi='Thêm ghi chú (tùy chọn)')
ui('save', en='Save', ja='保存', zh='保存', zh_Hant='儲存', ko='저장', de='Speichern', fr='Enregistrer', pt='Guardar', es='Guardar', it='Salva', hi='सहेजें', ar='حفظ', ca='Desa', hr='Spremi', cs='Uložit', da='Gem', nl='Opslaan', fi='Tallenna', el='Αποθήκευση', he='שמור', hu='Mentés', id='Simpan', ms='Simpan', no='Lagre', pl='Zapisz', ro='Salvează', ru='Сохранить', sk='Uložiť', sv='Spara', th='บันทึก', tr='Kaydet', uk='Зберегти', vi='Lưu')
ui('delete', en='Delete', ja='削除', zh='删除', zh_Hant='刪除', ko='삭제', de='Löschen', fr='Supprimer', pt='Eliminar', es='Eliminar', it='Elimina', hi='हटाएँ', ar='حذف', ca='Elimina', hr='Izbriši', cs='Smazat', da='Slet', nl='Verwijderen', fi='Poista', el='Διαγραφή', he='מחק', hu='Törlés', id='Hapus', ms='Padam', no='Slett', pl='Usuń', ro='Șterge', ru='Удалить', sk='Vymazať', sv='Radera', th='ลบ', tr='Sil', uk='Видалити', vi='Xóa')
ui('cancel', en='Cancel', ja='キャンセル', zh='取消', zh_Hant='取消', ko='취소', de='Abbrechen', fr='Annuler', pt='Cancelar', es='Cancelar', it='Annulla', hi='रद्द करें', ar='إلغاء', ca='Cancel·la', hr='Odustani', cs='Zrušit', da='Annuller', nl='Annuleren', fi='Peruuta', el='Άκυρο', he='ביטול', hu='Mégse', id='Batal', ms='Batal', no='Avbryt', pl='Anuluj', ro='Anulează', ru='Отмена', sk='Zrušiť', sv='Avbryt', th='ยกเลิก', tr='İptal', uk='Скасувати', vi='Hủy')
ui('milestoneSaved', en='Milestone saved', ja='記録を保存しました', zh='已保存里程碑', zh_Hant='已儲存里程碑', ko='기록을 저장했습니다', de='Meilenstein gespeichert', fr='Jalon enregistré', pt='Marco guardado', es='Hito guardado', it='Tappa salvata', hi='पड़ाव सहेजा गया', ar='تم حفظ الإنجاز', ca='Fita desada', hr='Prekretnica spremljena', cs='Milník uložen', da='Milepæl gemt', nl='Mijlpaal opgeslagen', fi='Virstanpylväs tallennettu', el='Αποθηκεύτηκε', he='אבן הדרך נשמרה', hu='Mentve', id='Tonggak disimpan', ms='Pencapaian disimpan', no='Milepæl lagret', pl='Zapisano', ro='Reper salvat', ru='Сохранено', sk='Míľnik uložený', sv='Milstolpe sparad', th='บันทึกแล้ว', tr='Kaydedildi', uk='Збережено', vi='Đã lưu cột mốc')
ui('selectCategory', en='All', ja='すべて', zh='全部', zh_Hant='全部', ko='전체', de='Alle', fr='Tous', pt='Todos', es='Todos', it='Tutti', hi='सभी', ar='الكل', ca='Tots', hr='Sve', cs='Vše', da='Alle', nl='Alle', fi='Kaikki', el='Όλα', he='הכול', hu='Mind', id='Semua', ms='Semua', no='Alle', pl='Wszystkie', ro='Toate', ru='Все', sk='Všetko', sv='Alla', th='ทั้งหมด', tr='Tümü', uk='Усі', vi='Tất cả')
ui('categoryMotor', en='Motor', ja='運動', zh='运动', zh_Hant='運動', ko='운동', de='Motorik', fr='Motricité', pt='Motor', es='Motor', it='Motorio', hi='शारीरिक', ar='حركي', ca='Motor', hr='Motorika', cs='Pohyb', da='Motorik', nl='Motoriek', fi='Motoriikka', el='Κινητικά', he='מוטורי', hu='Mozgás', id='Motorik', ms='Motor', no='Motorikk', pl='Ruch', ro='Motor', ru='Моторика', sk='Pohyb', sv='Motorik', th='การเคลื่อนไหว', tr='Motor', uk='Моторика', vi='Vận động')
ui('categoryLanguage', en='Language', ja='言語', zh='语言', zh_Hant='語言', ko='언어', de='Sprache', fr='Langage', pt='Linguagem', es='Lenguaje', it='Linguaggio', hi='भाषा', ar='اللغة', ca='Llenguatge', hr='Jezik', cs='Řeč', da='Sprog', nl='Taal', fi='Kieli', el='Γλώσσα', he='שפה', hu='Nyelv', id='Bahasa', ms='Bahasa', no='Språk', pl='Mowa', ro='Limbaj', ru='Речь', sk='Reč', sv='Språk', th='ภาษา', tr='Dil', uk='Мова', vi='Ngôn ngữ')
ui('categorySocial', en='Social', ja='社会性', zh='社交', zh_Hant='社交', ko='사회성', de='Sozial', fr='Social', pt='Social', es='Social', it='Sociale', hi='सामाजिक', ar='اجتماعي', ca='Social', hr='Društveno', cs='Sociální', da='Social', nl='Sociaal', fi='Sosiaalinen', el='Κοινωνικά', he='חברתי', hu='Társas', id='Sosial', ms='Sosial', no='Sosial', pl='Społeczne', ro='Social', ru='Социальное', sk='Sociálne', sv='Socialt', th='สังคม', tr='Sosyal', uk='Соціальне', vi='Xã hội')
ui('categoryCognitive', en='Cognitive', ja='認知', zh='认知', zh_Hant='認知', ko='인지', de='Kognitiv', fr='Cognitif', pt='Cognitivo', es='Cognitivo', it='Cognitivo', hi='संज्ञानात्मक', ar='إدراكي', ca='Cognitiu', hr='Spoznajno', cs='Poznávání', da='Kognitiv', nl='Cognitief', fi='Kognitiivinen', el='Γνωστικά', he='קוגניטיבי', hu='Kognitív', id='Kognitif', ms='Kognitif', no='Kognitiv', pl='Poznawcze', ro='Cognitiv', ru='Когнитивное', sk='Poznávanie', sv='Kognitiv', th='การรับรู้', tr='Bilişsel', uk='Когнітивне', vi='Nhận thức')
ui('cardSizePortrait', en='Portrait', ja='縦長', zh='竖版', zh_Hant='直式', ko='세로형', de='Hochformat', fr='Portrait', pt='Vertical', es='Vertical', it='Verticale', hi='पोर्ट्रेट', ar='عمودي', ca='Vertical', hr='Uspravno', cs='Na výšku', da='Stående', nl='Staand', fi='Pysty', el='Κατακόρυφο', he='לאורך', hu='Álló', id='Potret', ms='Potret', no='Stående', pl='Pionowo', ro='Portret', ru='Портрет', sk='Na výšku', sv='Stående', th='แนวตั้ง', tr='Dikey', uk='Портрет', vi='Dọc')
ui('cardSizeSquare', en='Square', ja='正方形', zh='方形', zh_Hant='方形', ko='정사각형', de='Quadrat', fr='Carré', pt='Quadrado', es='Cuadrado', it='Quadrato', hi='वर्ग', ar='مربع', ca='Quadrat', hr='Kvadrat', cs='Čtverec', da='Firkant', nl='Vierkant', fi='Neliö', el='Τετράγωνο', he='ריבוע', hu='Négyzet', id='Persegi', ms='Segi empat', no='Kvadrat', pl='Kwadrat', ro='Pătrat', ru='Квадрат', sk='Štvorec', sv='Kvadrat', th='สี่เหลี่ยม', tr='Kare', uk='Квадрат', vi='Vuông')
ui('cardSizeLandscape', en='Landscape', ja='横長', zh='横版', zh_Hant='橫式', ko='가로형', de='Querformat', fr='Paysage', pt='Horizontal', es='Horizontal', it='Orizzontale', hi='लैंडस्केप', ar='أفقي', ca='Horitzontal', hr='Vodoravno', cs='Na šířku', da='Liggende', nl='Liggend', fi='Vaaka', el='Οριζόντιο', he='לרוחב', hu='Fekvő', id='Lanskap', ms='Lanskap', no='Liggende', pl='Poziomo', ro='Peisaj', ru='Альбом', sk='Na šírku', sv='Liggande', th='แนวนอน', tr='Yatay', uk='Альбом', vi='Ngang')
ui('shareCard', en='Share', ja='共有', zh='分享', zh_Hant='分享', ko='공유', de='Teilen', fr='Partager', pt='Partilhar', es='Compartir', it='Condividi', hi='साझा करें', ar='مشاركة', ca='Comparteix', hr='Podijeli', cs='Sdílet', da='Del', nl='Delen', fi='Jaa', el='Κοινοποίηση', he='שתף', hu='Megosztás', id='Bagikan', ms='Kongsi', no='Del', pl='Udostępnij', ro='Distribuie', ru='Поделиться', sk='Zdieľať', sv='Dela', th='แชร์', tr='Paylaş', uk='Поділитися', vi='Chia sẻ')
ui('export4k', en='Export in 4K', ja='4Kで書き出す', zh='导出4K', zh_Hant='匯出4K', ko='4K로 내보내기', de='In 4K exportieren', fr='Exporter en 4K', pt='Exportar em 4K', es='Exportar en 4K', it='Esporta in 4K', hi='4K में निर्यात', ar='تصدير بدقة 4K', ca='Exporta en 4K', hr='Izvezi u 4K', cs='Exportovat ve 4K', da='Eksportér i 4K', nl='Exporteren in 4K', fi='Vie 4K-tarkkuudella', el='Εξαγωγή σε 4K', he='ייצוא ב-4K', hu='Exportálás 4K-ban', id='Ekspor 4K', ms='Eksport 4K', no='Eksporter i 4K', pl='Eksport 4K', ro='Exportă în 4K', ru='Экспорт в 4K', sk='Exportovať v 4K', sv='Exportera i 4K', th='ส่งออก 4K', tr='4K dışa aktar', uk='Експорт у 4K', vi='Xuất 4K')
ui('cardNoData', en='Record a milestone to create a card', ja='カードを作るには記録が必要です', zh='请先记录一个里程碑', zh_Hant='請先記錄一個里程碑', ko='카드를 만들려면 기록이 필요합니다', de='Erfasse einen Meilenstein für eine Karte', fr='Enregistrez un jalon pour créer une carte', pt='Registe um marco para criar um cartão', es='Registra un hito para crear una tarjeta', it='Registra una tappa per creare una carta', hi='कार्ड बनाने के लिए पड़ाव दर्ज करें', ar='سجّل إنجازًا لإنشاء بطاقة', ca='Registra una fita per crear una targeta', hr='Zabilježi prekretnicu za karticu', cs='Pro kartu zaznamenej milník', da='Registrer en milepæl for at lave et kort', nl='Leg een mijlpaal vast voor een kaart', fi='Tallenna virstanpylväs kortin luomiseksi', el='Καταγράψτε για να φτιάξετε κάρτα', he='תעד אבן דרך כדי ליצור כרטיס', hu='Rögzíts mérföldkövet a kártyához', id='Catat tonggak untuk membuat kartu', ms='Rekod pencapaian untuk buat kad', no='Registrer en milepæl for å lage et kort', pl='Zapisz kamień milowy, aby utworzyć kartę', ro='Înregistrează un reper pentru a crea un card', ru='Запишите событие, чтобы создать карточку', sk='Zaznamenaj míľnik pre kartu', sv='Registrera en milstolpe för att skapa kort', th='บันทึกความก้าวหน้าเพื่อสร้างการ์ด', tr='Kart için kilometre taşı kaydedin', uk='Запишіть подію, щоб створити картку', vi='Ghi cột mốc để tạo thẻ')
ui('onboardingNameTitle', en="What's your baby's name?", ja='お子さまの名前は？', zh='宝宝叫什么名字？', zh_Hant='寶寶叫什麼名字？', ko='아기 이름은 무엇인가요?', de='Wie heißt dein Baby?', fr='Quel est le nom de votre bébé ?', pt='Qual é o nome do bebé?', es='¿Cómo se llama tu bebé?', it='Come si chiama il tuo bambino?', hi='आपके शिशु का नाम क्या है?', ar='ما اسم طفلك؟', ca='Com es diu el teu nadó?', hr='Kako se zove vaša beba?', cs='Jak se jmenuje vaše dítě?', da='Hvad hedder din baby?', nl='Wat is de naam van je baby?', fi='Mikä on vauvasi nimi?', el='Πώς λέγεται το μωρό σας;', he='מה שם התינוק שלך?', hu='Hogy hívják a babát?', id='Siapa nama bayi Anda?', ms='Apa nama bayi anda?', no='Hva heter babyen din?', pl='Jak ma na imię Twoje dziecko?', ro='Cum se numește bebelușul?', ru='Как зовут вашего малыша?', sk='Ako sa volá vaše bábätko?', sv='Vad heter din bebis?', th='ลูกน้อยชื่ออะไร?', tr='Bebeğinizin adı ne?', uk='Як звати вашу дитину?', vi='Bé tên là gì?')
ui('onboardingNameHint', en="Baby's name", ja='お名前', zh='宝宝名字', zh_Hant='寶寶名字', ko='아기 이름', de='Name des Babys', fr='Nom du bébé', pt='Nome do bebé', es='Nombre del bebé', it='Nome del bambino', hi='शिशु का नाम', ar='اسم الطفل', ca='Nom del nadó', hr='Ime bebe', cs='Jméno dítěte', da='Babyens navn', nl='Naam baby', fi='Vauvan nimi', el='Όνομα μωρού', he='שם התינוק', hu='Baba neve', id='Nama bayi', ms='Nama bayi', no='Babyens navn', pl='Imię dziecka', ro='Numele bebelușului', ru='Имя малыша', sk='Meno bábätka', sv='Bebisens namn', th='ชื่อลูก', tr='Bebek adı', uk='Імʼя дитини', vi='Tên bé')
ui('onboardingBirthdayTitle', en="When was your baby born?", ja='お子さまの生年月日は？', zh='宝宝的出生日期？', zh_Hant='寶寶的出生日期？', ko='아기 생일은 언제인가요?', de='Wann wurde dein Baby geboren?', fr='Quand votre bébé est-il né ?', pt='Quando nasceu o bebé?', es='¿Cuándo nació tu bebé?', it='Quando è nato il tuo bambino?', hi='शिशु का जन्म कब हुआ?', ar='متى وُلد طفلك؟', ca='Quan va néixer el teu nadó?', hr='Kada je beba rođena?', cs='Kdy se vaše dítě narodilo?', da='Hvornår blev din baby født?', nl='Wanneer is je baby geboren?', fi='Milloin vauvasi syntyi?', el='Πότε γεννήθηκε το μωρό;', he='מתי נולד התינוק?', hu='Mikor született a baba?', id='Kapan bayi Anda lahir?', ms='Bila bayi anda lahir?', no='Når ble babyen din født?', pl='Kiedy urodziło się dziecko?', ro='Când s-a născut bebelușul?', ru='Когда родился ваш малыш?', sk='Kedy sa bábätko narodilo?', sv='När föddes din bebis?', th='ลูกเกิดเมื่อไหร่?', tr='Bebeğiniz ne zaman doğdu?', uk='Коли народилася дитина?', vi='Bé sinh khi nào?')
ui('onboardingFirstRecordTitle', en='Record your first milestone', ja='はじめての記録をしてみよう', zh='记录第一个里程碑', zh_Hant='記錄第一個里程碑', ko='첫 기록을 남겨보세요', de='Erfasse den ersten Meilenstein', fr='Enregistrez votre premier jalon', pt='Registe o primeiro marco', es='Registra tu primer hito', it='Registra la prima tappa', hi='पहला पड़ाव दर्ज करें', ar='سجّل أول إنجاز', ca='Registra la primera fita', hr='Zabilježi prvu prekretnicu', cs='Zaznamenej první milník', da='Registrer din første milepæl', nl='Leg je eerste mijlpaal vast', fi='Tallenna ensimmäinen virstanpylväs', el='Καταγράψτε το πρώτο σας ορόσημο', he='תעד את אבן הדרך הראשונה', hu='Rögzítsd az első mérföldkövet', id='Catat tonggak pertama', ms='Rekod pencapaian pertama', no='Registrer din første milepæl', pl='Zapisz pierwszy kamień milowy', ro='Înregistrează primul reper', ru='Запишите первое событие', sk='Zaznamenaj prvý míľnik', sv='Registrera din första milstolpe', th='บันทึกความก้าวหน้าแรก', tr='İlk kilometre taşını kaydedin', uk='Запишіть першу подію', vi='Ghi cột mốc đầu tiên')
ui('getStarted', en='Get Started', ja='はじめる', zh='开始', zh_Hant='開始', ko='시작하기', de='Loslegen', fr='Commencer', pt='Começar', es='Empezar', it='Inizia', hi='शुरू करें', ar='ابدأ', ca='Comença', hr='Započni', cs='Začít', da='Kom i gang', nl='Aan de slag', fi='Aloita', el='Ξεκινήστε', he='בואו נתחיל', hu='Kezdés', id='Mulai', ms='Mula', no='Kom i gang', pl='Rozpocznij', ro='Începe', ru='Начать', sk='Začať', sv='Kom igång', th='เริ่ม', tr='Başla', uk='Почати', vi='Bắt đầu')
ui('notificationSetting', en='Notifications', ja='通知設定', zh='通知设置', zh_Hant='通知設定', ko='알림 설정', de='Benachrichtigungen', fr='Notifications', pt='Notificações', es='Notificaciones', it='Notifiche', hi='सूचनाएँ', ar='الإشعارات', ca='Notificacions', hr='Obavijesti', cs='Oznámení', da='Notifikationer', nl='Meldingen', fi='Ilmoitukset', el='Ειδοποιήσεις', he='התראות', hu='Értesítések', id='Notifikasi', ms='Pemberitahuan', no='Varsler', pl='Powiadomienia', ro='Notificări', ru='Уведомления', sk='Oznámenia', sv='Aviseringar', th='การแจ้งเตือน', tr='Bildirimler', uk='Сповіщення', vi='Thông báo')
ui('manageBabies', en='Manage Children', ja='お子さまの管理', zh='管理孩子', zh_Hant='管理孩子', ko='아이 관리', de='Kinder verwalten', fr='Gérer les enfants', pt='Gerir crianças', es='Gestionar niños', it='Gestisci bambini', hi='बच्चे प्रबंधित करें', ar='إدارة الأطفال', ca='Gestiona els fills', hr='Upravljanje djecom', cs='Správa dětí', da='Administrer børn', nl='Kinderen beheren', fi='Hallitse lapsia', el='Διαχείριση παιδιών', he='ניהול ילדים', hu='Gyermekek kezelése', id='Kelola anak', ms='Urus anak', no='Administrer barn', pl='Zarządzaj dziećmi', ro='Gestionează copiii', ru='Управление детьми', sk='Správa detí', sv='Hantera barn', th='จัดการเด็ก', tr='Çocukları yönet', uk='Керування дітьми', vi='Quản lý bé')
ui('addChild', en='Add Child', ja='お子さまを追加', zh='添加孩子', zh_Hant='新增孩子', ko='아이 추가', de='Kind hinzufügen', fr='Ajouter un enfant', pt='Adicionar criança', es='Añadir niño', it='Aggiungi bambino', hi='बच्चा जोड़ें', ar='إضافة طفل', ca='Afegeix un fill', hr='Dodaj dijete', cs='Přidat dítě', da='Tilføj barn', nl='Kind toevoegen', fi='Lisää lapsi', el='Προσθήκη παιδιού', he='הוסף ילד', hu='Gyermek hozzáadása', id='Tambah anak', ms='Tambah anak', no='Legg til barn', pl='Dodaj dziecko', ro='Adaugă copil', ru='Добавить ребёнка', sk='Pridať dieťa', sv='Lägg till barn', th='เพิ่มเด็ก', tr='Çocuk ekle', uk='Додати дитину', vi='Thêm bé')
ui('milestoneUpcomingTitle', en='A new milestone is coming!', ja='新しい発達の節目が近づいています', zh='新的发育节点即将到来！', zh_Hant='新的發育節點即將到來！', ko='새로운 발달 시기가 다가와요!', de='Ein neuer Meilenstein steht bevor!', fr='Un nouveau jalon approche !', pt='Um novo marco está a chegar!', es='¡Se acerca un nuevo hito!', it='Sta arrivando una nuova tappa!', hi='एक नया पड़ाव आ रहा है!', ar='يقترب إنجاز جديد!', ca='Arriba una nova fita!', hr='Stiže nova prekretnica!', cs='Blíží se nový milník!', da='En ny milepæl er på vej!', nl='Een nieuwe mijlpaal komt eraan!', fi='Uusi virstanpylväs lähestyy!', el='Έρχεται νέο ορόσημο!', he='אבן דרך חדשה מתקרבת!', hu='Új mérföldkő közeleg!', id='Tonggak baru akan datang!', ms='Pencapaian baharu akan tiba!', no='En ny milepæl nærmer seg!', pl='Nadchodzi nowy kamień milowy!', ro='Urmează un nou reper!', ru='Приближается новое событие!', sk='Blíži sa nový míľnik!', sv='En ny milstolpe närmar sig!', th='ก้าวสำคัญใหม่กำลังมา!', tr='Yeni bir kilometre taşı yaklaşıyor!', uk='Наближається нова подія!', vi='Một cột mốc mới sắp đến!')
ui('milestoneUpcomingBody', en='Your baby is reaching {months} months. Check the new milestones!', ja='お子さまは生後{months}ヶ月になります。新しい発達目安をチェックしましょう！', zh='宝宝即将{months}个月，快来看看新的发育目标吧！', zh_Hant='寶寶即將{months}個月，快來看看新的發育目標吧！', ko='아기가 {months}개월이 됩니다. 새로운 발달 목표를 확인하세요!', de='Dein Baby wird {months} Monate alt. Sieh dir die neuen Meilensteine an!', fr='Votre bébé atteint {months} mois. Découvrez les nouveaux jalons !', pt='O bebé chega aos {months} meses. Veja os novos marcos!', es='Tu bebé cumple {months} meses. ¡Mira los nuevos hitos!', it='Il tuo bambino compie {months} mesi. Scopri le nuove tappe!', hi='आपका शिशु {months} माह का हो रहा है। नए पड़ाव देखें!', ar='طفلك يبلغ {months} أشهر. تحقق من الإنجازات الجديدة!', ca='El teu nadó arriba als {months} mesos. Mira les noves fites!', hr='Vaša beba navršava {months} mj. Provjerite nove prekretnice!', cs='Vašemu dítěti je {months} měsíců. Podívejte se na nové milníky!', da='Din baby fylder {months} måneder. Tjek de nye milepæle!', nl='Je baby wordt {months} maanden. Bekijk de nieuwe mijlpalen!', fi='Vauvasi täyttää {months} kk. Katso uudet virstanpylväät!', el='Το μωρό σας γίνεται {months} μηνών. Δείτε τα νέα ορόσημα!', he='התינוק שלך מגיע לגיל {months} חודשים. בדוק את אבני הדרך החדשות!', hu='A baba {months} hónapos lesz. Nézd meg az új mérföldköveket!', id='Bayi Anda mencapai {months} bulan. Lihat tonggak baru!', ms='Bayi anda mencecah {months} bulan. Semak pencapaian baharu!', no='Babyen din fyller {months} måneder. Sjekk de nye milepælene!', pl='Twoje dziecko kończy {months} mies. Sprawdź nowe kamienie milowe!', ro='Bebelușul tău împlinește {months} luni. Vezi noile repere!', ru='Малышу исполняется {months} мес. Посмотрите новые события!', sk='Vaše bábätko má {months} mesiacov. Pozrite si nové míľniky!', sv='Din bebis fyller {months} månader. Kolla de nya milstolparna!', th='ลูกกำลังจะ {months} เดือน มาดูพัฒนาการใหม่กันเถอะ!', tr='Bebeğiniz {months} ayı buluyor. Yeni kilometre taşlarına bakın!', uk='Малюку виповнюється {months} міс. Перегляньте нові події!', vi='Bé sắp tròn {months} tháng. Xem các cột mốc mới nhé!', _ph={'months': {'type': 'int'}})

# ---- Milestone preset titles ----
# Provided for major markets; other locales fall back to English term.
MS = collections.OrderedDict()

def ms(key, en, ja, zh, zh_Hant, ko, de, fr, pt, es, it, hi):
    MS[key] = dict(en=en, ja=ja, zh=zh, zh_Hant=zh_Hant, ko=ko, de=de,
                   fr=fr, pt=pt, es=es, it=it, hi=hi)

ms('milestoneFirstGaze','First eye contact','はじめてのアイコンタクト','第一次眼神接触','第一次眼神接觸','첫 눈맞춤','Erster Blickkontakt','Premier contact visuel','Primeiro contacto visual','Primer contacto visual','Primo contatto visivo','पहली नज़र')
ms('milestoneReactToSound','Reacts to sound','音に反応','对声音有反应','對聲音有反應','소리에 반응','Reagiert auf Geräusche','Réagit au son','Reage ao som','Reacciona al sonido','Reagisce ai suoni','आवाज़ पर प्रतिक्रिया')
ms('milestoneFirstCryMeaning','Different cries','泣き分け','不同的哭声','不同的哭聲','다른 울음','Verschiedene Schreie','Pleurs différenciés','Choros diferentes','Llantos distintos','Pianti diversi','अलग-अलग रोना')
ms('milestoneGraspReflex','Grasp reflex','把握反射','抓握反射','抓握反射','쥐는 반사','Greifreflex','Réflexe de préhension','Reflexo de preensão','Reflejo de prensión','Riflesso di presa','पकड़ प्रतिवर्त')
ms('milestoneFirstSmile','First smile','はじめての笑顔','第一次微笑','第一次微笑','첫 미소','Erstes Lächeln','Premier sourire','Primeiro sorriso','Primera sonrisa','Primo sorriso','पहली मुस्कान')
ms('milestoneLiftHead','Lifts head','首を持ち上げる','抬头','抬頭','고개 들기','Hebt den Kopf','Lève la tête','Levanta a cabeça','Levanta la cabeza','Solleva la testa','सिर उठाना')
ms('milestoneCooSound','Cooing','クーイング','咿呀发声','咿呀發聲','옹알이','Gurren','Gazouillis','Arrulhos','Gorjeos','Vocalizzi','कूइंग')
ms('milestoneFollowObject','Follows objects','物を目で追う','追视物体','追視物體','물체 따라보기','Folgt Objekten','Suit des objets','Segue objetos','Sigue objetos','Segue gli oggetti','वस्तु का अनुसरण')
ms('milestoneSocialSmile','Social smile','あやすと笑う','社交性微笑','社交性微笑','사회적 미소','Soziales Lächeln','Sourire social','Sorriso social','Sonrisa social','Sorriso sociale','सामाजिक मुस्कान')
ms('milestoneHoldHeadSteady','Holds head steady','首がすわる','稳定抬头','穩定抬頭','목 가누기','Hält Kopf stabil','Tient sa tête','Sustenta a cabeça','Sostiene la cabeza','Tiene la testa ferma','सिर स्थिर')
ms('milestoneLaughOutLoud','Laughs out loud','声を出して笑う','咯咯大笑','咯咯大笑','소리 내어 웃기','Lacht laut','Rit aux éclats','Ri alto','Ríe a carcajadas','Ride forte','खिलखिलाकर हँसना')
ms('milestoneReachForToy','Reaches for toys','おもちゃに手を伸ばす','伸手够玩具','伸手夠玩具','장난감 잡기','Greift nach Spielzeug','Attrape les jouets','Alcança brinquedos','Alcanza juguetes','Afferra i giochi','खिलौने तक पहुँचना')
ms('milestoneBabble','Babbles','喃語','咿呀学语','咿呀學語','옹알이 시작','Brabbelt','Babille','Balbucia','Balbucea','Lallazione','बड़बड़ाना')
ms('milestoneRecognizeParent','Recognizes parents','親を認識','认得父母','認得父母','부모 알아보기','Erkennt Eltern','Reconnaît ses parents','Reconhece os pais','Reconoce a los padres','Riconosce i genitori','माता-पिता को पहचानना')
ms('milestoneRollover','Rolls over','寝返り','翻身','翻身','뒤집기','Dreht sich um','Se retourne','Vira-se','Se da la vuelta','Si gira','करवट लेना')
ms('milestoneGrabObject','Grabs objects','物をつかむ','抓住物体','抓住物體','물건 잡기','Greift Objekte','Saisit des objets','Agarra objetos','Agarra objetos','Afferra oggetti','वस्तु पकड़ना')
ms('milestoneSitWithSupport','Sits with support','支えありで座る','扶坐','扶坐','받쳐 앉기','Sitzt mit Stütze','S’assoit avec appui','Senta com apoio','Se sienta con apoyo','Si siede con sostegno','सहारे से बैठना')
ms('milestoneRespondToName','Responds to name','名前に反応','回应名字','回應名字','이름에 반응','Reagiert auf Namen','Répond à son nom','Responde ao nome','Responde a su nombre','Risponde al nome','नाम पर प्रतिक्रिया')
ms('milestoneMouthObject','Explores with mouth','口で確かめる','用嘴探索','用嘴探索','입으로 탐색','Erkundet mit Mund','Explore avec la bouche','Explora com a boca','Explora con la boca','Esplora con la bocca','मुँह से खोज')
ms('milestoneFirstSolidFood','First solid food','はじめての離乳食','第一次辅食','第一次副食品','첫 이유식','Erste feste Nahrung','Première nourriture solide','Primeira papa','Primer alimento sólido','Primo cibo solido','पहला ठोस आहार')
ms('milestoneSitUnaided','Sits unaided','ひとりで座る','独坐','獨坐','혼자 앉기','Sitzt allein','S’assoit seul','Senta sozinho','Se sienta solo','Si siede da solo','बिना सहारे बैठना')
ms('milestoneCrawl','Crawls','ハイハイ','爬行','爬行','기어가기','Krabbelt','Rampe','Gatinha','Gatea','Gattona','रेंगना')
ms('milestoneFirstTooth','First tooth','はじめての歯','第一颗牙','第一顆牙','첫 이','Erster Zahn','Première dent','Primeiro dente','Primer diente','Primo dentino','पहला दाँत')
ms('milestoneSayMamaPapa','Says mama/papa','ママ・パパと言う','叫爸爸妈妈','叫爸爸媽媽','엄마/아빠 부르기','Sagt Mama/Papa','Dit maman/papa','Diz mamã/papá','Dice mamá/papá','Dice mamma/papà','मामा/पापा कहना')
ms('milestoneWaveBye','Waves bye-bye','バイバイする','挥手再见','揮手再見','빠이빠이','Winkt zum Abschied','Fait au revoir','Acena adeus','Dice adiós con la mano','Saluta con la mano','बाय-बाय करना')
ms('milestonePassObject','Passes object hand to hand','物を持ち替える','两手传递物体','兩手傳遞物體','손에서 손으로 옮기기','Gibt Objekt weiter','Passe d’une main à l’autre','Passa de mão em mão','Pasa de mano a mano','Passa da mano a mano','हाथ बदलना')
ms('milestonePeekaboo','Plays peekaboo','いないいないばあ','玩躲猫猫','玩躲貓貓','까꿍 놀이','Spielt Kuckuck','Joue à coucou','Brinca às escondidas','Juega al cucú','Gioca a bubu','छुपा-छुपी खेलना')
ms('milestonePullToStand','Pulls to stand','つかまり立ち','扶站','扶站','잡고 서기','Zieht sich hoch','Se met debout','Põe-se de pé','Se pone de pie','Si tira su','सहारा लेकर खड़ा होना')
ms('milestoneCruiseFurniture','Cruises furniture','つたい歩き','扶物行走','扶物行走','가구 짚고 걷기','Läuft an Möbeln entlang','Marche en s’appuyant','Anda apoiado','Camina apoyado','Cammina appoggiandosi','सहारे से चलना')
ms('milestonePincerGrasp','Pincer grasp','指先でつまむ','拇指食指捏取','拇指食指捏取','집게 잡기','Pinzettengriff','Pince pouce-index','Pinça fina','Pinza fina','Presa a pinza','चुटकी पकड़')
ms('milestoneClapHands','Claps hands','拍手する','拍手','拍手','박수 치기','Klatscht','Tape des mains','Bate palmas','Aplaude','Batte le mani','ताली बजाना')
ms('milestoneUnderstandNo','Understands "no"','「だめ」がわかる','听懂"不行"','聽懂「不行」','"안돼" 이해','Versteht „nein“','Comprend « non »','Entende o "não"','Entiende el "no"','Capisce il "no"','"नहीं" समझना')
ms('milestonePointAtThings','Points at things','指さし','用手指指物','用手指指物','손가락으로 가리키기','Zeigt auf Dinge','Pointe du doigt','Aponta','Señala','Indica con il dito','उँगली से इशारा')
ms('milestoneFirstSteps','First steps','はじめての一歩','第一步','第一步','첫 걸음','Erste Schritte','Premiers pas','Primeiros passos','Primeros pasos','Primi passi','पहला कदम')
ms('milestoneFirstWord','First word','はじめての言葉','第一个词','第一個詞','첫 단어','Erstes Wort','Premier mot','Primeira palavra','Primera palabra','Prima parola','पहला शब्द')
ms('milestoneDrinkFromCup','Drinks from cup','コップで飲む','用杯子喝水','用杯子喝水','컵으로 마시기','Trinkt aus Becher','Boit à la tasse','Bebe pelo copo','Bebe de la taza','Beve dal bicchiere','कप से पीना')
ms('milestoneStackBlocks','Stacks blocks','積み木を重ねる','叠积木','疊積木','블록 쌓기','Stapelt Bauklötze','Empile des cubes','Empilha blocos','Apila bloques','Impila i blocchi','ब्लॉक जमाना')
ms('milestoneWalkWell','Walks well','上手に歩く','走得稳','走得穩','잘 걷기','Läuft gut','Marche bien','Anda bem','Camina bien','Cammina bene','अच्छे से चलना')
ms('milestoneUseSpoon','Uses a spoon','スプーンを使う','用勺子','用湯匙','숟가락 사용','Benutzt Löffel','Utilise une cuillère','Usa a colher','Usa la cuchara','Usa il cucchiaio','चम्मच का उपयोग')
ms('milestoneFollowInstruction','Follows instructions','指示に従う','听从指令','聽從指令','지시 따르기','Befolgt Anweisungen','Suit des consignes','Segue instruções','Sigue instrucciones','Segue le istruzioni','निर्देश मानना')
ms('milestoneRun','Runs','走る','跑步','跑步','달리기','Rennt','Court','Corre','Corre','Corre','दौड़ना')
ms('milestoneTwoWordPhrase','Two-word phrases','2語文','两词短语','兩詞短語','두 단어 문장','Zweiwortsätze','Phrases de deux mots','Frases de duas palavras','Frases de dos palabras','Frasi di due parole','दो-शब्द वाक्य')
ms('milestoneKickBall','Kicks a ball','ボールを蹴る','踢球','踢球','공 차기','Tritt einen Ball','Tape dans un ballon','Chuta a bola','Patea la pelota','Calcia la palla','गेंद को लात मारना')
ms('milestoneScribble','Scribbles','なぐり書き','涂鸦','塗鴉','낙서하기','Kritzelt','Gribouille','Rabisca','Garabatea','Scarabocchia','चित्र बनाना')
ms('milestoneNameBodyParts','Names body parts','体の部位を言う','说出身体部位','說出身體部位','신체 부위 말하기','Benennt Körperteile','Nomme les parties du corps','Nomeia partes do corpo','Nombra partes del cuerpo','Nomina parti del corpo','शरीर के अंग बताना')
ms('milestonePretendPlay','Pretend play','ごっこ遊び','假装游戏','假裝遊戲','상상 놀이','Rollenspiel','Jeu d’imitation','Faz de conta','Juego simbólico','Gioco di finzione','कल्पना का खेल')
ms('milestoneJump','Jumps','ジャンプする','跳跃','跳躍','점프하기','Springt','Saute','Salta','Salta','Salta','कूदना')
ms('milestoneShortSentence','Short sentences','短い文を話す','说短句','說短句','짧은 문장','Kurze Sätze','Phrases courtes','Frases curtas','Frases cortas','Frasi brevi','छोटे वाक्य')
ms('milestoneNameColors','Names colors','色の名前を言う','说出颜色','說出顏色','색깔 말하기','Benennt Farben','Nomme les couleurs','Nomeia cores','Nombra colores','Nomina i colori','रंग बताना')
ms('milestoneSortShapes','Sorts shapes','形を分ける','分类形状','分類形狀','모양 분류','Sortiert Formen','Trie les formes','Separa formas','Clasifica formas','Ordina le forme','आकृतियाँ छाँटना')
ms('milestonePottyTraining','Potty training','トイレトレーニング','如厕训练','如廁訓練','배변 훈련','Sauberkeitstraining','Apprentissage de la propreté','Treino do bacio','Aprende a usar el orinal','Spannolinamento','पॉटी प्रशिक्षण')
ms('milestonePlayWithOthers','Plays with others','お友達と遊ぶ','和他人玩耍','和他人玩耍','친구와 놀기','Spielt mit anderen','Joue avec les autres','Brinca com outros','Juega con otros','Gioca con altri','दूसरों के साथ खेलना')
ms('milestoneClimbStairs','Climbs stairs','階段をのぼる','爬楼梯','爬樓梯','계단 오르기','Steigt Treppen','Monte les escaliers','Sobe escadas','Sube escaleras','Sale le scale','सीढ़ियाँ चढ़ना')


def build_entries(locale):
    """Return ordered dict of new key->value for a given ARB file suffix."""
    base = FILES[locale]  # base locale used for UI strings
    out = collections.OrderedDict()
    # UI strings
    for key, vals in UI.items():
        val = vals.get(base) or vals.get('en')
        out[key] = ('ui', val, vals.get('_ph'))
    # Milestone titles
    for key, vals in MS.items():
        val = vals.get(base) or vals['en']
        out[key] = ('ms', val, None)
    return out


def main():
    for fname in sorted(os.listdir(L10N_DIR)):
        if not fname.endswith('.arb'):
            continue
        suffix = fname[len('app_'):-len('.arb')]
        if suffix not in FILES:
            continue
        path = os.path.join(L10N_DIR, fname)
        with open(path, encoding='utf-8') as f:
            data = json.load(f, object_pairs_hook=collections.OrderedDict)
        is_template = (suffix == 'en')
        entries = build_entries(suffix)
        for key, (kind, val, ph) in entries.items():
            data[key] = val
            if is_template:
                meta = {'description': f'{kind} string {key}'}
                if ph:
                    meta['placeholders'] = ph
                data['@' + key] = meta
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write('\n')
        print(f'updated {fname}: +{len(entries)} keys')


if __name__ == '__main__':
    main()
